export interface LGA {
  name: string;
  id: string;
}

export interface State {
  name: string;
  id: string;
  lgas: LGA[];
}

export const nigeriaStatesAndLGAs: State[] = [
  {
    name: 'Abia',
    id: 'abia',
    lgas: [
      { name: 'Aba North', id: 'aba-north' },
      { name: 'Aba South', id: 'aba-south' },
      { name: 'Arochukwu', id: 'arochukwu' },
      { name: 'Bende', id: 'bende' },
      { name: 'Ikwuano', id: 'ikwuano' },
      { name: 'Isiala Ngwa North', id: 'isiala-ngwa-north' },
      { name: 'Isiala Ngwa South', id: 'isiala-ngwa-south' },
      { name: 'Isuikwuato', id: 'isuikwuato' },
      { name: 'Obi Ngwa', id: 'obi-ngwa' },
      { name: 'Ohafia', id: 'ohafia' },
      { name: 'Osisioma', id: 'osisioma' },
      { name: 'Ugwunagbo', id: 'ugwunagbo' },
      { name: 'Ukwa East', id: 'ukwa-east' },
      { name: 'Ukwa West', id: 'ukwa-west' },
      { name: 'Umuahia North', id: 'umuahia-north' },
      { name: 'Umuahia South', id: 'umuahia-south' },
      { name: 'Umu Nneochi', id: 'umu-nneochi' },
    ],
  },
  {
    name: 'Adamawa',
    id: 'adamawa',
    lgas: [
      { name: 'Demsa', id: 'demsa' },
      { name: 'Fufure', id: 'fufure' },
      { name: 'Ganye', id: 'ganye' },
      { name: 'Gayuk', id: 'gayuk' },
      { name: 'Gombi', id: 'gombi' },
      { name: 'Grie', id: 'grie' },
      { name: 'Hong', id: 'hong' },
      { name: 'Jada', id: 'jada' },
      { name: 'Lamurde', id: 'lamurde' },
      { name: 'Madagali', id: 'madagali' },
      { name: 'Maiha', id: 'maiha' },
      { name: 'Mayo Belwa', id: 'mayo-belwa' },
      { name: 'Michika', id: 'michika' },
      { name: 'Mubi North', id: 'mubi-north' },
      { name: 'Mubi South', id: 'mubi-south' },
      { name: 'Numan', id: 'numan' },
      { name: 'Shelleng', id: 'shelleng' },
      { name: 'Song', id: 'song' },
      { name: 'Toungo', id: 'toungo' },
      { name: 'Yola North', id: 'yola-north' },
      { name: 'Yola South', id: 'yola-south' },
    ],
  },
  {
    name: 'Akwa Ibom',
    id: 'akwa-ibom',
    lgas: [
      { name: 'Abak', id: 'abak' },
      { name: 'Eastern Obolo', id: 'eastern-obolo' },
      { name: 'Eket', id: 'eket' },
      { name: 'Esit Eket', id: 'esit-eket' },
      { name: 'Essien Udim', id: 'essien-udim' },
      { name: 'Etim Ekpo', id: 'etim-ekpo' },
      { name: 'Etinan', id: 'etinan' },
      { name: 'Ibeno', id: 'ibeno' },
      { name: 'Ibesikpo Asutan', id: 'ibesikpo-asutan' },
      { name: 'Ibiono-Ibom', id: 'ibiono-ibom' },
      { name: 'Ika', id: 'ika' },
      { name: 'Ikono', id: 'ikono' },
      { name: 'Ikot Abasi', id: 'ikot-abasi' },
      { name: 'Ikot Ekpene', id: 'ikot-ekpene' },
      { name: 'Ini', id: 'ini' },
      { name: 'Itu', id: 'itu' },
      { name: 'Mbo', id: 'mbo' },
      { name: 'Mkpat-Enin', id: 'mkpat-enin' },
      { name: 'Nsit-Atai', id: 'nsit-atai' },
      { name: 'Nsit-Ibom', id: 'nsit-ibom' },
      { name: 'Nsit-Ubium', id: 'nsit-ubium' },
      { name: 'Obot Akara', id: 'obot-akara' },
      { name: 'Okobo', id: 'okobo' },
      { name: 'Onna', id: 'onna' },
      { name: 'Oron', id: 'oron' },
      { name: 'Oruk Anam', id: 'oruk-anam' },
      { name: 'Udung-Uko', id: 'udung-uko' },
      { name: 'Ukanafun', id: 'ukanafun' },
      { name: 'Uruan', id: 'uruan' },
      { name: 'Urue-Offong/Oruko', id: 'urue-offong-oruko' },
      { name: 'Uyo', id: 'uyo' },
    ],
  },
  {
    name: 'Anambra',
    id: 'anambra',
    lgas: [
      { name: 'Aguata', id: 'aguata' },
      { name: 'Anambra East', id: 'anambra-east' },
      { name: 'Anambra West', id: 'anambra-west' },
      { name: 'Anaocha', id: 'anaocha' },
      { name: 'Awka North', id: 'awka-north' },
      { name: 'Awka South', id: 'awka-south' },
      { name: 'Ayamelum', id: 'ayamelum' },
      { name: 'Dunukofia', id: 'dunukofia' },
      { name: 'Ekwusigo', id: 'ekwusigo' },
      { name: 'Idemili North', id: 'idemili-north' },
      { name: 'Idemili South', id: 'idemili-south' },
      { name: 'Ihiala', id: 'ihiala' },
      { name: 'Njikoka', id: 'njikoka' },
      { name: 'Nnewi North', id: 'nnewi-north' },
      { name: 'Nnewi South', id: 'nnewi-south' },
      { name: 'Ogbaru', id: 'ogbaru' },
      { name: 'Onitsha North', id: 'onitsha-north' },
      { name: 'Onitsha South', id: 'onitsha-south' },
      { name: 'Orumba North', id: 'orumba-north' },
      { name: 'Orumba South', id: 'orumba-south' },
      { name: 'Oyi', id: 'oyi' },
    ],
  },
  {
    name: 'Bauchi',
    id: 'bauchi',
    lgas: [
      { name: 'Alkaleri', id: 'alkaleri' },
      { name: 'Bauchi', id: 'bauchi' },
      { name: 'Bogoro', id: 'bogoro' },
      { name: 'Damban', id: 'damban' },
      { name: 'Darazo', id: 'darazo' },
      { name: 'Dass', id: 'dass' },
      { name: 'Gamawa', id: 'gamawa' },
      { name: 'Ganjuwa', id: 'ganjuwa' },
      { name: 'Giade', id: 'giade' },
      { name: 'Itas/Gadau', id: 'itas-gadau' },
      { name: "Jama'are", id: 'jama-are' },
      { name: 'Katagum', id: 'katagum' },
      { name: 'Kirfi', id: 'kirfi' },
      { name: 'Misau', id: 'misau' },
      { name: 'Ningi', id: 'ningi' },
      { name: 'Shira', id: 'shira' },
      { name: 'Tafawa Balewa', id: 'tafawa-balewa' },
      { name: 'Toro', id: 'toro' },
      { name: 'Warji', id: 'warji' },
      { name: 'Zaki', id: 'zaki' },
    ],
  },
  {
    name: 'Bayelsa',
    id: 'bayelsa',
    lgas: [
      { name: 'Brass', id: 'brass' },
      { name: 'Ekeremor', id: 'ekeremor' },
      { name: 'Kolokuma/Opokuma', id: 'kolokuma-opokuma' },
      { name: 'Nembe', id: 'nembe' },
      { name: 'Ogbia', id: 'ogbia' },
      { name: 'Sagbama', id: 'sagbama' },
      { name: 'Southern Ijaw', id: 'southern-ijaw' },
      { name: 'Yenagoa', id: 'yenagoa' },
    ],
  },
  {
    name: 'Benue',
    id: 'benue',
    lgas: [
      { name: 'Ado', id: 'ado' },
      { name: 'Agatu', id: 'agatu' },
      { name: 'Apa', id: 'apa' },
      { name: 'Buruku', id: 'buruku' },
      { name: 'Gboko', id: 'gboko' },
      { name: 'Guma', id: 'guma' },
      { name: 'Gwer East', id: 'gwer-east' },
      { name: 'Gwer West', id: 'gwer-west' },
      { name: 'Katsina-Ala', id: 'katsina-ala' },
      { name: 'Konshisha', id: 'konshisha' },
      { name: 'Kwande', id: 'kwande' },
      { name: 'Logo', id: 'logo' },
      { name: 'Makurdi', id: 'makurdi' },
      { name: 'Obi', id: 'obi' },
      { name: 'Ogbadibo', id: 'ogbadibo' },
      { name: 'Ohimini', id: 'ohimini' },
      { name: 'Oju', id: 'oju' },
      { name: 'Okpokwu', id: 'okpokwu' },
      { name: 'Otukpo', id: 'otukpo' },
      { name: 'Tarka', id: 'tarka' },
      { name: 'Ukum', id: 'ukum' },
      { name: 'Ushongo', id: 'ushongo' },
      { name: 'Vandeikya', id: 'vandeikya' },
    ],
  },
  {
    name: 'Borno',
    id: 'borno',
    lgas: [
      { name: 'Abadam', id: 'abadam' },
      { name: 'Askira/Uba', id: 'askira-uba' },
      { name: 'Bama', id: 'bama' },
      { name: 'Bayo', id: 'bayo' },
      { name: 'Biu', id: 'biu' },
      { name: 'Chibok', id: 'chibok' },
      { name: 'Damboa', id: 'damboa' },
      { name: 'Dikwa', id: 'dikwa' },
      { name: 'Gubio', id: 'gubio' },
      { name: 'Guzamala', id: 'guzamala' },
      { name: 'Gwoza', id: 'gwoza' },
      { name: 'Hawul', id: 'hawul' },
      { name: 'Jere', id: 'jere' },
      { name: 'Kaga', id: 'kaga' },
      { name: 'Kala/Balge', id: 'kala-balge' },
      { name: 'Konduga', id: 'konduga' },
      { name: 'Kukawa', id: 'kukawa' },
      { name: 'Kwaya Kusar', id: 'kwaya-kusar' },
      { name: 'Mafa', id: 'mafa' },
      { name: 'Magumeri', id: 'magumeri' },
      { name: 'Maiduguri', id: 'maiduguri' },
      { name: 'Marte', id: 'marte' },
      { name: 'Mobbar', id: 'mobbar' },
      { name: 'Monguno', id: 'monguno' },
      { name: 'Ngala', id: 'ngala' },
      { name: 'Nganzai', id: 'nganzai' },
      { name: 'Shani', id: 'shani' },
    ],
  },
  {
    name: 'Cross River',
    id: 'cross-river',
    lgas: [
      { name: 'Abi', id: 'abi' },
      { name: 'Akamkpa', id: 'akamkpa' },
      { name: 'Akpabuyo', id: 'akpabuyo' },
      { name: 'Bakassi', id: 'bakassi' },
      { name: 'Bekwarra', id: 'bekwarra' },
      { name: 'Biase', id: 'biase' },
      { name: 'Boki', id: 'boki' },
      { name: 'Calabar Municipal', id: 'calabar-municipal' },
      { name: 'Calabar South', id: 'calabar-south' },
      { name: 'Etung', id: 'etung' },
      { name: 'Ikom', id: 'ikom' },
      { name: 'Obanliku', id: 'obanliku' },
      { name: 'Obubra', id: 'obubra' },
      { name: 'Obudu', id: 'obudu' },
      { name: 'Odukpani', id: 'odukpani' },
      { name: 'Ogoja', id: 'ogoja' },
      { name: 'Yakuur', id: 'yakuur' },
      { name: 'Yala', id: 'yala' },
    ],
  },
  {
    name: 'Delta',
    id: 'delta',
    lgas: [
      { name: 'Aniocha North', id: 'aniocha-north' },
      { name: 'Aniocha South', id: 'aniocha-south' },
      { name: 'Bomadi', id: 'bomadi' },
      { name: 'Burutu', id: 'burutu' },
      { name: 'Ethiope East', id: 'ethiope-east' },
      { name: 'Ethiope West', id: 'ethiope-west' },
      { name: 'Ika North East', id: 'ika-north-east' },
      { name: 'Ika South', id: 'ika-south' },
      { name: 'Isoko North', id: 'isoko-north' },
      { name: 'Isoko South', id: 'isoko-south' },
      { name: 'Ndokwa East', id: 'ndokwa-east' },
      { name: 'Ndokwa West', id: 'ndokwa-west' },
      { name: 'Okpe', id: 'okpe' },
      { name: 'Oshimili North', id: 'oshimili-north' },
      { name: 'Oshimili South', id: 'oshimili-south' },
      { name: 'Patani', id: 'patani' },
      { name: 'Sapele', id: 'sapele' },
      { name: 'Udu', id: 'udu' },
      { name: 'Ughelli North', id: 'ughelli-north' },
      { name: 'Ughelli South', id: 'ughelli-south' },
      { name: 'Ukwuani', id: 'ukwuani' },
      { name: 'Uvwie', id: 'uvwie' },
      { name: 'Warri North', id: 'warri-north' },
      { name: 'Warri South', id: 'warri-south' },
      { name: 'Warri South West', id: 'warri-south-west' },
    ],
  },
  {
    name: 'Ebonyi',
    id: 'ebonyi',
    lgas: [
      { name: 'Abakaliki', id: 'abakaliki' },
      { name: 'Afikpo North', id: 'afikpo-north' },
      { name: 'Afikpo South', id: 'afikpo-south' },
      { name: 'Ebonyi', id: 'ebonyi' },
      { name: 'Ezza North', id: 'ezza-north' },
      { name: 'Ezza South', id: 'ezza-south' },
      { name: 'Ikwo', id: 'ikwo' },
      { name: 'Ishielu', id: 'ishielu' },
      { name: 'Ivo', id: 'ivo' },
      { name: 'Izzi', id: 'izzi' },
      { name: 'Ohaozara', id: 'ohaozara' },
      { name: 'Ohaukwu', id: 'ohaukwu' },
      { name: 'Onicha', id: 'onicha' },
    ],
  },
  {
    name: 'Edo',
    id: 'edo',
    lgas: [
      { name: 'Akoko-Edo', id: 'akoko-edo' },
      { name: 'Egor', id: 'egor' },
      { name: 'Esan Central', id: 'esan-central' },
      { name: 'Esan North-East', id: 'esan-north-east' },
      { name: 'Esan South-East', id: 'esan-south-east' },
      { name: 'Esan West', id: 'esan-west' },
      { name: 'Etsako Central', id: 'etsako-central' },
      { name: 'Etsako East', id: 'etsako-east' },
      { name: 'Etsako West', id: 'etsako-west' },
      { name: 'Igueben', id: 'igueben' },
      { name: 'Ikpoba Okha', id: 'ikpoba-okha' },
      { name: 'Orhionmwon', id: 'orhionmwon' },
      { name: 'Oredo', id: 'oredo' },
      { name: 'Ovia North-East', id: 'ovia-north-east' },
      { name: 'Ovia South-West', id: 'ovia-south-west' },
      { name: 'Owan East', id: 'owan-east' },
      { name: 'Owan West', id: 'owan-west' },
      { name: 'Uhunmwonde', id: 'uhunmwonde' },
    ],
  },
  {
    name: 'Ekiti',
    id: 'ekiti',
    lgas: [
      { name: 'Ado Ekiti', id: 'ado-ekiti' },
      { name: 'Efon', id: 'efon' },
      { name: 'Ekiti East', id: 'ekiti-east' },
      { name: 'Ekiti South-West', id: 'ekiti-south-west' },
      { name: 'Ekiti West', id: 'ekiti-west' },
      { name: 'Emure', id: 'emure' },
      { name: 'Gbonyin', id: 'gbonyin' },
      { name: 'Ido Osi', id: 'ido-osi' },
      { name: 'Ijero', id: 'ijero' },
      { name: 'Ikere', id: 'ikere' },
      { name: 'Ikole', id: 'ikole' },
      { name: 'Ilejemeje', id: 'ilejemeje' },
      { name: 'Irepodun/Ifelodun', id: 'irepodun-ifelodun' },
      { name: 'Ise/Orun', id: 'ise-orun' },
      { name: 'Moba', id: 'moba' },
      { name: 'Oye', id: 'oye' },
    ],
  },
  {
    name: 'Enugu',
    id: 'enugu',
    lgas: [
      { name: 'Aninri', id: 'aninri' },
      { name: 'Awgu', id: 'awgu' },
      { name: 'Enugu East', id: 'enugu-east' },
      { name: 'Enugu North', id: 'enugu-north' },
      { name: 'Enugu South', id: 'enugu-south' },
      { name: 'Ezeagu', id: 'ezeagu' },
      { name: 'Igbo Etiti', id: 'igbo-etiti' },
      { name: 'Igbo Eze North', id: 'igbo-eze-north' },
      { name: 'Igbo Eze South', id: 'igbo-eze-south' },
      { name: 'Isi Uzo', id: 'isi-uzo' },
      { name: 'Nkanu East', id: 'nkanu-east' },
      { name: 'Nkanu West', id: 'nkanu-west' },
      { name: 'Nsukka', id: 'nsukka' },
      { name: 'Oji River', id: 'oji-river' },
      { name: 'Udenu', id: 'udenu' },
      { name: 'Udi', id: 'udi' },
      { name: 'Uzo Uwani', id: 'uzo-uwani' },
    ],
  },
  {
    name: 'Gombe',
    id: 'gombe',
    lgas: [
      { name: 'Akko', id: 'akko' },
      { name: 'Balanga', id: 'balanga' },
      { name: 'Billiri', id: 'billiri' },
      { name: 'Dukku', id: 'dukku' },
      { name: 'Funakaye', id: 'funakaye' },
      { name: 'Gombe', id: 'gombe' },
      { name: 'Kaltungo', id: 'kaltungo' },
      { name: 'Kwami', id: 'kwami' },
      { name: 'Nafada', id: 'nafada' },
      { name: 'Shongom', id: 'shongom' },
      { name: 'Yamaltu/Deba', id: 'yamaltu-deba' },
    ],
  },
  {
    name: 'Imo',
    id: 'imo',
    lgas: [
      { name: 'Aboh Mbaise', id: 'aboh-mbaise' },
      { name: 'Ahiazu Mbaise', id: 'ahiazu-mbaise' },
      { name: 'Ehime Mbano', id: 'ehime-mbano' },
      { name: 'Ezinihitte', id: 'ezinihitte' },
      { name: 'Ideato North', id: 'ideato-north' },
      { name: 'Ideato South', id: 'ideato-south' },
      { name: 'Ihitte/Uboma', id: 'ihitte-uboma' },
      { name: 'Ikeduru', id: 'ikeduru' },
      { name: 'Isiala Mbano', id: 'isiala-mbano' },
      { name: 'Isu', id: 'isu' },
      { name: 'Mbaitoli', id: 'mbaitoli' },
      { name: 'Ngor Okpala', id: 'ngor-okpala' },
      { name: 'Njaba', id: 'njaba' },
      { name: 'Nkwerre', id: 'nkwerre' },
      { name: 'Nwangele', id: 'nwangele' },
      { name: 'Obowo', id: 'obowo' },
      { name: 'Oguta', id: 'oguta' },
      { name: 'Ohaji/Egbema', id: 'ohaji-egbema' },
      { name: 'Okigwe', id: 'okigwe' },
      { name: 'Orlu', id: 'orlu' },
      { name: 'Orsu', id: 'orsu' },
      { name: 'Oru East', id: 'oru-east' },
      { name: 'Oru West', id: 'oru-west' },
      { name: 'Owerri Municipal', id: 'owerri-municipal' },
      { name: 'Owerri North', id: 'owerri-north' },
      { name: 'Owerri West', id: 'owerri-west' },
      { name: 'Unuimo', id: 'unuimo' },
    ],
  },
  {
    name: 'Jigawa',
    id: 'jigawa',
    lgas: [
      { name: 'Auyo', id: 'auyo' },
      { name: 'Babura', id: 'babura' },
      { name: 'Biriniwa', id: 'biriniwa' },
      { name: 'Birnin Kudu', id: 'birnin-kudu' },
      { name: 'Buji', id: 'buji' },
      { name: 'Dutse', id: 'dutse' },
      { name: 'Gagarawa', id: 'gagarawa' },
      { name: 'Garki', id: 'garki' },
      { name: 'Gumel', id: 'gumel' },
      { name: 'Guri', id: 'guri' },
      { name: 'Gwaram', id: 'gwaram' },
      { name: 'Gwiwa', id: 'gwiwa' },
      { name: 'Hadejia', id: 'hadejia' },
      { name: 'Jahun', id: 'jahun' },
      { name: 'Kafin Hausa', id: 'kafin-hausa' },
      { name: 'Kazaure', id: 'kazaure' },
      { name: 'Kiri Kasama', id: 'kiri-kasama' },
      { name: 'Kiyawa', id: 'kiyawa' },
      { name: 'Maigatari', id: 'maigatari' },
      { name: 'Malam Madori', id: 'malam-madori' },
      { name: 'Miga', id: 'miga' },
      { name: 'Ringim', id: 'ringim' },
      { name: 'Roni', id: 'roni' },
      { name: 'Sule Tankarkar', id: 'sule-tankarkar' },
      { name: 'Taura', id: 'taura' },
      { name: 'Yankwashi', id: 'yankwashi' },
    ],
  },
  {
    name: 'Kaduna',
    id: 'kaduna',
    lgas: [
      { name: 'Birnin Gwari', id: 'birnin-gwari' },
      { name: 'Chikun', id: 'chikun' },
      { name: 'Giwa', id: 'giwa' },
      { name: 'Igabi', id: 'igabi' },
      { name: 'Ikara', id: 'ikara' },
      { name: 'Jaba', id: 'jaba' },
      { name: "Jema'a", id: 'jema-a' },
      { name: 'Kachia', id: 'kachia' },
      { name: 'Kaduna North', id: 'kaduna-north' },
      { name: 'Kaduna South', id: 'kaduna-south' },
      { name: 'Kagarko', id: 'kagarko' },
      { name: 'Kajuru', id: 'kajuru' },
      { name: 'Kaura', id: 'kaura' },
      { name: 'Kauru', id: 'kauru' },
      { name: 'Kubau', id: 'kubau' },
      { name: 'Kudan', id: 'kudan' },
      { name: 'Lere', id: 'lere' },
      { name: 'Makarfi', id: 'makarfi' },
      { name: 'Sabon Gari', id: 'sabon-gari' },
      { name: 'Sanga', id: 'sanga' },
      { name: 'Soba', id: 'soba' },
      { name: 'Zangon Kataf', id: 'zangon-kataf' },
      { name: 'Zaria', id: 'zaria' },
    ],
  },
  {
    name: 'Kano',
    id: 'kano',
    lgas: [
      { name: 'Ajingi', id: 'ajingi' },
      { name: 'Albasu', id: 'albasu' },
      { name: 'Bagwai', id: 'bagwai' },
      { name: 'Bebeji', id: 'bebeji' },
      { name: 'Bichi', id: 'bichi' },
      { name: 'Bunkure', id: 'bunkure' },
      { name: 'Dala', id: 'dala' },
      { name: 'Dambatta', id: 'dambatta' },
      { name: 'Dawakin Kudu', id: 'dawakin-kudu' },
      { name: 'Dawakin Tofa', id: 'dawakin-tofa' },
      { name: 'Doguwa', id: 'doguwa' },
      { name: 'Fagge', id: 'fagge' },
      { name: 'Gabasawa', id: 'gabasawa' },
      { name: 'Garko', id: 'garko' },
      { name: 'Garun Mallam', id: 'garun-mallam' },
      { name: 'Gaya', id: 'gaya' },
      { name: 'Gezawa', id: 'gezawa' },
      { name: 'Gwale', id: 'gwale' },
      { name: 'Gwarzo', id: 'gwarzo' },
      { name: 'Kabo', id: 'kabo' },
      { name: 'Kano Municipal', id: 'kano-municipal' },
      { name: 'Karaye', id: 'karaye' },
      { name: 'Kibiya', id: 'kibiya' },
      { name: 'Kiru', id: 'kiru' },
      { name: 'Kumbotso', id: 'kumbotso' },
      { name: 'Kunchi', id: 'kunchi' },
      { name: 'Kura', id: 'kura' },
      { name: 'Madobi', id: 'madobi' },
      { name: 'Makoda', id: 'makoda' },
      { name: 'Minjibir', id: 'minjibir' },
      { name: 'Nasarawa', id: 'nasarawa' },
      { name: 'Rano', id: 'rano' },
      { name: 'Rimin Gado', id: 'rimin-gado' },
      { name: 'Rogo', id: 'rogo' },
      { name: 'Shanono', id: 'shanono' },
      { name: 'Sumaila', id: 'sumaila' },
      { name: 'Takai', id: 'takai' },
      { name: 'Tarauni', id: 'tarauni' },
      { name: 'Tofa', id: 'tofa' },
      { name: 'Tsanyawa', id: 'tsanyawa' },
      { name: 'Tudun Wada', id: 'tudun-wada' },
      { name: 'Ungogo', id: 'ungogo' },
      { name: 'Warawa', id: 'warawa' },
      { name: 'Wudil', id: 'wudil' },
    ],
  },
  {
    name: 'Katsina',
    id: 'katsina',
    lgas: [
      { name: 'Bakori', id: 'bakori' },
      { name: 'Batagarawa', id: 'batagarawa' },
      { name: 'Batsari', id: 'batsari' },
      { name: 'Baure', id: 'baure' },
      { name: 'Bindawa', id: 'bindawa' },
      { name: 'Charanchi', id: 'charanchi' },
      { name: 'Dandume', id: 'dandume' },
      { name: 'Danja', id: 'danja' },
      { name: 'Dan Musa', id: 'dan-musa' },
      { name: 'Daura', id: 'daura' },
      { name: 'Dutsi', id: 'dutsi' },
      { name: 'Dutsin Ma', id: 'dutsin-ma' },
      { name: 'Faskari', id: 'faskari' },
      { name: 'Funtua', id: 'funtua' },
      { name: 'Ingawa', id: 'ingawa' },
      { name: 'Jibia', id: 'jibia' },
      { name: 'Kafur', id: 'kafur' },
      { name: 'Kaita', id: 'kaita' },
      { name: 'Kankara', id: 'kankara' },
      { name: 'Kankia', id: 'kankia' },
      { name: 'Katsina', id: 'katsina' },
      { name: 'Kurfi', id: 'kurfi' },
      { name: 'Kusada', id: 'kusada' },
      { name: "Mai'Adua", id: 'mai-adua' },
      { name: 'Malumfashi', id: 'malumfashi' },
      { name: 'Mani', id: 'mani' },
      { name: 'Mashi', id: 'mashi' },
      { name: 'Matazu', id: 'matazu' },
      { name: 'Musawa', id: 'musawa' },
      { name: 'Rimi', id: 'rimi' },
      { name: 'Sabuwa', id: 'sabuwa' },
      { name: 'Safana', id: 'safana' },
      { name: 'Sandamu', id: 'sandamu' },
      { name: 'Zango', id: 'zango' },
    ],
  },
  {
    name: 'Kebbi',
    id: 'kebbi',
    lgas: [
      { name: 'Aleiro', id: 'aleiro' },
      { name: 'Arewa Dandi', id: 'arewa-dandi' },
      { name: 'Argungu', id: 'argungu' },
      { name: 'Augie', id: 'augie' },
      { name: 'Bagudo', id: 'bagudo' },
      { name: 'Birnin Kebbi', id: 'birnin-kebbi' },
      { name: 'Bunza', id: 'bunza' },
      { name: 'Dandi', id: 'dandi' },
      { name: 'Fakai', id: 'fakai' },
      { name: 'Gwandu', id: 'gwandu' },
      { name: 'Jega', id: 'jega' },
      { name: 'Kalgo', id: 'kalgo' },
      { name: 'Koko/Besse', id: 'koko-besse' },
      { name: 'Maiyama', id: 'maiyama' },
      { name: 'Ngaski', id: 'ngaski' },
      { name: 'Sakaba', id: 'sakaba' },
      { name: 'Shanga', id: 'shanga' },
      { name: 'Suru', id: 'suru' },
      { name: 'Wasagu/Danko', id: 'wasagu-danko' },
      { name: 'Yauri', id: 'yauri' },
      { name: 'Zuru', id: 'zuru' },
    ],
  },
  {
    name: 'Kogi',
    id: 'kogi',
    lgas: [
      { name: 'Adavi', id: 'adavi' },
      { name: 'Ajaokuta', id: 'ajaokuta' },
      { name: 'Ankpa', id: 'ankpa' },
      { name: 'Bassa', id: 'bassa' },
      { name: 'Dekina', id: 'dekina' },
      { name: 'Ibaji', id: 'ibaji' },
      { name: 'Idah', id: 'idah' },
      { name: 'Igalamela Odolu', id: 'igalamela-odolu' },
      { name: 'Ijumu', id: 'ijumu' },
      { name: 'Kabba/Bunu', id: 'kabba-bunu' },
      { name: 'Kogi', id: 'kogi' },
      { name: 'Lokoja', id: 'lokoja' },
      { name: 'Mopa Muro', id: 'mopa-muro' },
      { name: 'Ofu', id: 'ofu' },
      { name: 'Ogori/Magongo', id: 'ogori-magongo' },
      { name: 'Okehi', id: 'okehi' },
      { name: 'Okene', id: 'okene' },
      { name: 'Olamaboro', id: 'olamaboro' },
      { name: 'Omala', id: 'omala' },
      { name: 'Yagba East', id: 'yagba-east' },
      { name: 'Yagba West', id: 'yagba-west' },
    ],
  },
  {
    name: 'Kwara',
    id: 'kwara',
    lgas: [
      { name: 'Asa', id: 'asa' },
      { name: 'Baruten', id: 'baruten' },
      { name: 'Edu', id: 'edu' },
      { name: 'Ekiti', id: 'ekiti-kwara' },
      { name: 'Ifelodun', id: 'ifelodun-kwara' },
      { name: 'Ilorin East', id: 'ilorin-east' },
      { name: 'Ilorin South', id: 'ilorin-south' },
      { name: 'Ilorin West', id: 'ilorin-west' },
      { name: 'Irepodun', id: 'irepodun-kwara' },
      { name: 'Isin', id: 'isin' },
      { name: 'Kaiama', id: 'kaiama' },
      { name: 'Moro', id: 'moro' },
      { name: 'Offa', id: 'offa' },
      { name: 'Oke Ero', id: 'oke-ero' },
      { name: 'Oyun', id: 'oyun' },
      { name: 'Pategi', id: 'pategi' },
    ],
  },
  {
    name: 'Lagos',
    id: 'lagos',
    lgas: [
      { name: 'Agege', id: 'agege' },
      { name: 'Ajeromi-Ifelodun', id: 'ajeromi-ifelodun' },
      { name: 'Alimosho', id: 'alimosho' },
      { name: 'Amuwo-Odofin', id: 'amuwo-odofin' },
      { name: 'Apapa', id: 'apapa' },
      { name: 'Badagry', id: 'badagry' },
      { name: 'Epe', id: 'epe' },
      { name: 'Eti-Osa', id: 'eti-osa' },
      { name: 'Ibeju-Lekki', id: 'ibeju-lekki' },
      { name: 'Ifako-Ijaiye', id: 'ifako-ijaiye' },
      { name: 'Ikeja', id: 'ikeja' },
      { name: 'Ikorodu', id: 'ikorodu' },
      { name: 'Kosofe', id: 'kosofe' },
      { name: 'Lagos Island', id: 'lagos-island' },
      { name: 'Lagos Mainland', id: 'lagos-mainland' },
      { name: 'Mushin', id: 'mushin' },
      { name: 'Ojo', id: 'ojo' },
      { name: 'Oshodi-Isolo', id: 'oshodi-isolo' },
      { name: 'Shomolu', id: 'shomolu' },
      { name: 'Surulere', id: 'surulere' },
    ],
  },
  {
    name: 'Nasarawa',
    id: 'nasarawa',
    lgas: [
      { name: 'Akwanga', id: 'akwanga' },
      { name: 'Awe', id: 'awe' },
      { name: 'Doma', id: 'doma' },
      { name: 'Karu', id: 'karu' },
      { name: 'Keana', id: 'keana' },
      { name: 'Keffi', id: 'keffi' },
      { name: 'Kokona', id: 'kokona' },
      { name: 'Lafia', id: 'lafia' },
      { name: 'Nasarawa', id: 'nasarawa-lga' },
      { name: 'Nasarawa Egon', id: 'nasarawa-egon' },
      { name: 'Obi', id: 'obi-nasarawa' },
      { name: 'Toto', id: 'toto' },
      { name: 'Wamba', id: 'wamba' },
    ],
  },
  {
    name: 'Niger',
    id: 'niger',
    lgas: [
      { name: 'Agaie', id: 'agaie' },
      { name: 'Agwara', id: 'agwara' },
      { name: 'Bida', id: 'bida' },
      { name: 'Borgu', id: 'borgu' },
      { name: 'Bosso', id: 'bosso' },
      { name: 'Chanchaga', id: 'chanchaga' },
      { name: 'Edati', id: 'edati' },
      { name: 'Gbako', id: 'gbako' },
      { name: 'Gurara', id: 'gurara' },
      { name: 'Katcha', id: 'katcha' },
      { name: 'Kontagora', id: 'kontagora' },
      { name: 'Lapai', id: 'lapai' },
      { name: 'Lavun', id: 'lavun' },
      { name: 'Magama', id: 'magama' },
      { name: 'Mariga', id: 'mariga' },
      { name: 'Mashegu', id: 'mashegu' },
      { name: 'Mokwa', id: 'mokwa' },
      { name: 'Moya', id: 'moya' },
      { name: 'Paikoro', id: 'paikoro' },
      { name: 'Rafi', id: 'rafi' },
      { name: 'Rijau', id: 'rijau' },
      { name: 'Shiroro', id: 'shiroro' },
      { name: 'Suleja', id: 'suleja' },
      { name: 'Tafa', id: 'tafa' },
      { name: 'Wushishi', id: 'wushishi' },
    ],
  },
  {
    name: 'Ogun',
    id: 'ogun',
    lgas: [
      { name: 'Abeokuta North', id: 'abeokuta-north' },
      { name: 'Abeokuta South', id: 'abeokuta-south' },
      { name: 'Ado-Odo/Ota', id: 'ado-odo-ota' },
      { name: 'Egbado North', id: 'egbado-north' },
      { name: 'Egbado South', id: 'egbado-south' },
      { name: 'Ewekoro', id: 'ewekoro' },
      { name: 'Ifo', id: 'ifo' },
      { name: 'Ijebu East', id: 'ijebu-east' },
      { name: 'Ijebu North', id: 'ijebu-north' },
      { name: 'Ijebu North East', id: 'ijebu-north-east' },
      { name: 'Ijebu Ode', id: 'ijebu-ode' },
      { name: 'Ikenne', id: 'ikenne' },
      { name: 'Imeko Afon', id: 'imeko-afon' },
      { name: 'Ipokia', id: 'ipokia' },
      { name: 'Obafemi Owode', id: 'obafemi-owode' },
      { name: 'Odeda', id: 'odeda' },
      { name: 'Odogbolu', id: 'odogbolu' },
      { name: 'Ogun Waterside', id: 'ogun-waterside' },
      { name: 'Remo North', id: 'remo-north' },
      { name: 'Shagamu', id: 'shagamu' },
    ],
  },
  {
    name: 'Ondo',
    id: 'ondo',
    lgas: [
      { name: 'Akoko North-East', id: 'akoko-north-east' },
      { name: 'Akoko North-West', id: 'akoko-north-west' },
      { name: 'Akoko South-East', id: 'akoko-south-east' },
      { name: 'Akoko South-West', id: 'akoko-south-west' },
      { name: 'Akure North', id: 'akure-north' },
      { name: 'Akure South', id: 'akure-south' },
      { name: 'Ese Odo', id: 'ese-odo' },
      { name: 'Idanre', id: 'idanre' },
      { name: 'Ifedore', id: 'ifedore' },
      { name: 'Ilaje', id: 'ilaje' },
      { name: 'Ile Oluji/Okeigbo', id: 'ile-oluji-okeigbo' },
      { name: 'Irele', id: 'irele' },
      { name: 'Odigbo', id: 'odigbo' },
      { name: 'Okitipupa', id: 'okitipupa' },
      { name: 'Ondo East', id: 'ondo-east' },
      { name: 'Ondo West', id: 'ondo-west' },
      { name: 'Ose', id: 'ose' },
      { name: 'Owo', id: 'owo' },
    ],
  },
  {
    name: 'Osun',
    id: 'osun',
    lgas: [
      { name: 'Aiyedaade', id: 'aiyedaade' },
      { name: 'Aiyedire', id: 'aiyedire' },
      { name: 'Atakunmosa East', id: 'atakunmosa-east' },
      { name: 'Atakunmosa West', id: 'atakunmosa-west' },
      { name: 'Boluwaduro', id: 'boluwaduro' },
      { name: 'Boripe', id: 'boripe' },
      { name: 'Ede North', id: 'ede-north' },
      { name: 'Ede South', id: 'ede-south' },
      { name: 'Egbedore', id: 'egbedore' },
      { name: 'Ejigbo', id: 'ejigbo' },
      { name: 'Ife Central', id: 'ife-central' },
      { name: 'Ife East', id: 'ife-east' },
      { name: 'Ife North', id: 'ife-north' },
      { name: 'Ife South', id: 'ife-south' },
      { name: 'Ifedayo', id: 'ifedayo' },
      { name: 'Ifelodun', id: 'ifelodun-osun' },
      { name: 'Ila', id: 'ila' },
      { name: 'Ilesa East', id: 'ilesa-east' },
      { name: 'Ilesa West', id: 'ilesa-west' },
      { name: 'Irepodun', id: 'irepodun-osun' },
      { name: 'Irewole', id: 'irewole' },
      { name: 'Isokan', id: 'isokan' },
      { name: 'Iwo', id: 'iwo' },
      { name: 'Obokun', id: 'obokun' },
      { name: 'Odo Otin', id: 'odo-otin' },
      { name: 'Ola Oluwa', id: 'ola-oluwa' },
      { name: 'Olorunda', id: 'olorunda' },
      { name: 'Oriade', id: 'oriade' },
      { name: 'Orolu', id: 'orolu' },
      { name: 'Osogbo', id: 'osogbo' },
    ],
  },
  {
    name: 'Oyo',
    id: 'oyo',
    lgas: [
      { name: 'Afijio', id: 'afijio' },
      { name: 'Akinyele', id: 'akinyele' },
      { name: 'Atiba', id: 'atiba' },
      { name: 'Atisbo', id: 'atisbo' },
      { name: 'Egbeda', id: 'egbeda' },
      { name: 'Ibadan North', id: 'ibadan-north' },
      { name: 'Ibadan North-East', id: 'ibadan-north-east' },
      { name: 'Ibadan North-West', id: 'ibadan-north-west' },
      { name: 'Ibadan South-East', id: 'ibadan-south-east' },
      { name: 'Ibadan South-West', id: 'ibadan-south-west' },
      { name: 'Ibarapa Central', id: 'ibarapa-central' },
      { name: 'Ibarapa East', id: 'ibarapa-east' },
      { name: 'Ibarapa North', id: 'ibarapa-north' },
      { name: 'Ido', id: 'ido' },
      { name: 'Irepo', id: 'irepo' },
      { name: 'Iseyin', id: 'iseyin' },
      { name: 'Itesiwaju', id: 'itesiwaju' },
      { name: 'Iwajowa', id: 'iwajowa' },
      { name: 'Kajola', id: 'kajola' },
      { name: 'Lagelu', id: 'lagelu' },
      { name: 'Ogbomosho North', id: 'ogbomosho-north' },
      { name: 'Ogbomosho South', id: 'ogbomosho-south' },
      { name: 'Ogo Oluwa', id: 'ogo-oluwa' },
      { name: 'Olorunsogo', id: 'olorunsogo' },
      { name: 'Oluyole', id: 'oluyole' },
      { name: 'Ona Ara', id: 'ona-ara' },
      { name: 'Orelope', id: 'orelope' },
      { name: 'Ori Ire', id: 'ori-ire' },
      { name: 'Oyo', id: 'oyo' },
      { name: 'Oyo East', id: 'oyo-east' },
      { name: 'Saki East', id: 'saki-east' },
      { name: 'Saki West', id: 'saki-west' },
      { name: 'Surulere', id: 'surulere-oyo' },
    ],
  },
  {
    name: 'Plateau',
    id: 'plateau',
    lgas: [
      { name: 'Barkin Ladi', id: 'barkin-ladi' },
      { name: 'Bassa', id: 'bassa-plateau' },
      { name: 'Bokkos', id: 'bokkos' },
      { name: 'Jos East', id: 'jos-east' },
      { name: 'Jos North', id: 'jos-north' },
      { name: 'Jos South', id: 'jos-south' },
      { name: 'Kanam', id: 'kanam' },
      { name: 'Kanke', id: 'kanke' },
      { name: 'Langtang North', id: 'langtang-north' },
      { name: 'Langtang South', id: 'langtang-south' },
      { name: 'Mangu', id: 'mangu' },
      { name: 'Mikang', id: 'mikang' },
      { name: 'Pankshin', id: 'pankshin' },
      { name: "Qua'an Pan", id: 'qua-an-pan' },
      { name: 'Riyom', id: 'riyom' },
      { name: 'Shendam', id: 'shendam' },
      { name: 'Wase', id: 'wase' },
    ],
  },
  {
    name: 'Rivers',
    id: 'rivers',
    lgas: [
      { name: 'Abua/Odual', id: 'abua-odual' },
      { name: 'Ahoada East', id: 'ahoada-east' },
      { name: 'Ahoada West', id: 'ahoada-west' },
      { name: 'Akuku-Toru', id: 'akuku-toru' },
      { name: 'Andoni', id: 'andoni' },
      { name: 'Asari-Toru', id: 'asari-toru' },
      { name: 'Bonny', id: 'bonny' },
      { name: 'Degema', id: 'degema' },
      { name: 'Eleme', id: 'eleme' },
      { name: 'Emuoha', id: 'emuoha' },
      { name: 'Etche', id: 'etche' },
      { name: 'Gokana', id: 'gokana' },
      { name: 'Ikwerre', id: 'ikwerre' },
      { name: 'Khana', id: 'khana' },
      { name: 'Obio/Akpor', id: 'obio-akpor' },
      { name: 'Ogba/Egbema/Ndoni', id: 'ogba-egbema-ndoni' },
      { name: 'Ogu/Bolo', id: 'ogu-bolo' },
      { name: 'Okrika', id: 'okrika' },
      { name: 'Omuma', id: 'omuma' },
      { name: 'Opobo/Nkoro', id: 'opobo-nkoro' },
      { name: 'Oyigbo', id: 'oyigbo' },
      { name: 'Port Harcourt', id: 'port-harcourt' },
      { name: 'Tai', id: 'tai' },
    ],
  },
  {
    name: 'Sokoto',
    id: 'sokoto',
    lgas: [
      { name: 'Binji', id: 'binji' },
      { name: 'Bodinga', id: 'bodinga' },
      { name: 'Dange Shuni', id: 'dange-shuni' },
      { name: 'Gada', id: 'gada' },
      { name: 'Goronyo', id: 'goronyo' },
      { name: 'Gudu', id: 'gudu' },
      { name: 'Gwadabawa', id: 'gwadabawa' },
      { name: 'Illela', id: 'illela' },
      { name: 'Isa', id: 'isa' },
      { name: 'Kebbe', id: 'kebbe' },
      { name: 'Kware', id: 'kware' },
      { name: 'Rabah', id: 'rabah' },
      { name: 'Sabon Birni', id: 'sabon-birni' },
      { name: 'Shagari', id: 'shagari' },
      { name: 'Silame', id: 'silame' },
      { name: 'Sokoto North', id: 'sokoto-north' },
      { name: 'Sokoto South', id: 'sokoto-south' },
      { name: 'Tambuwal', id: 'tambuwal' },
      { name: 'Tangaza', id: 'tangaza' },
      { name: 'Tureta', id: 'tureta' },
      { name: 'Wamako', id: 'wamako' },
      { name: 'Wurno', id: 'wurno' },
      { name: 'Yabo', id: 'yabo' },
    ],
  },
  {
    name: 'Taraba',
    id: 'taraba',
    lgas: [
      { name: 'Ardo Kola', id: 'ardo-kola' },
      { name: 'Bali', id: 'bali' },
      { name: 'Donga', id: 'donga' },
      { name: 'Gashaka', id: 'gashaka' },
      { name: 'Gassol', id: 'gassol' },
      { name: 'Ibi', id: 'ibi' },
      { name: 'Jalingo', id: 'jalingo' },
      { name: 'Karim Lamido', id: 'karim-lamido' },
      { name: 'Kumi', id: 'kumi' },
      { name: 'Lau', id: 'lau' },
      { name: 'Sardauna', id: 'sardauna' },
      { name: 'Takum', id: 'takum' },
      { name: 'Ussa', id: 'ussa' },
      { name: 'Wukari', id: 'wukari' },
      { name: 'Yorro', id: 'yorro' },
      { name: 'Zing', id: 'zing' },
    ],
  },
  {
    name: 'Yobe',
    id: 'yobe',
    lgas: [
      { name: 'Bade', id: 'bade' },
      { name: 'Bursari', id: 'bursari' },
      { name: 'Damaturu', id: 'damaturu' },
      { name: 'Fika', id: 'fika' },
      { name: 'Fune', id: 'fune' },
      { name: 'Geidam', id: 'geidam' },
      { name: 'Gujba', id: 'gujba' },
      { name: 'Gulani', id: 'gulani' },
      { name: 'Jakusko', id: 'jakusko' },
      { name: 'Karasuwa', id: 'karasuwa' },
      { name: 'Machina', id: 'machina' },
      { name: 'Nangere', id: 'nangere' },
      { name: 'Nguru', id: 'nguru' },
      { name: 'Potiskum', id: 'potiskum' },
      { name: 'Tarmuwa', id: 'tarmuwa' },
      { name: 'Yunusari', id: 'yunusari' },
      { name: 'Yusufari', id: 'yusufari' },
    ],
  },
  {
    name: 'Zamfara',
    id: 'zamfara',
    lgas: [
      { name: 'Anka', id: 'anka' },
      { name: 'Bakura', id: 'bakura' },
      { name: 'Birnin Magaji/Kiyaw', id: 'birnin-magaji-kiyaw' },
      { name: 'Bukkuyum', id: 'bukkuyum' },
      { name: 'Bungudu', id: 'bungudu' },
      { name: 'Gummi', id: 'gummi' },
      { name: 'Gusau', id: 'gusau' },
      { name: 'Kaura Namoda', id: 'kaura-namoda' },
      { name: 'Maradun', id: 'maradun' },
      { name: 'Maru', id: 'maru' },
      { name: 'Shinkafi', id: 'shinkafi' },
      { name: 'Talata Mafara', id: 'talata-mafara' },
      { name: 'Zurmi', id: 'zurmi' },
    ],
  },
  {
    name: 'FCT Abuja',
    id: 'fct',
    lgas: [
      { name: 'Abaji', id: 'abaji' },
      { name: 'Bwari', id: 'bwari' },
      { name: 'Gwagwalada', id: 'gwagwalada' },
      { name: 'Kuje', id: 'kuje' },
      { name: 'Kwali', id: 'kwali' },
      { name: 'Municipal Area Council', id: 'municipal' },
    ],
  },
];

export const getStates = () => {
  return nigeriaStatesAndLGAs.map((state) => ({
    label: state.name,
    value: state.id,
  }));
};

export const getLGAs = (stateId: string) => {
  const state = nigeriaStatesAndLGAs.find((s) => s.id === stateId);
  if (!state) return [];

  return state.lgas.map((lga) => ({
    label: lga.name,
    value: lga.id,
  }));
};
